language: c
matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      env: BUILDTYPE=Debug
    - os: linux
      dist: bionic
      compiler: gcc
      env: BUILDTYPE=Release
    - os: linux
      dist: bionic
      compiler: clang
      env: BUILDTYPE=Debug
    - os: linux
      dist: bionic
      compiler: clang
      env: BUILDTYPE=Release
    - os: linux
      dist: bionic
      addons:
        apt:
          update: true
          packages:
            - musl-tools
      env: BUILDTYPE=Debug CC=musl-gcc LINK=musl-gcc
    - os: osx
      env: BUILDTYPE=Debug
    - os: osx
      env: BUILDTYPE=Release
script:
  - make
  - ./build/quv -e "console.log('hello world');"
branches:
  only:
    - master
