language: c
matrix:
  include:
    - name: Linux GCC embedded-CURL Debug
      os: linux
      dist: bionic
      compiler: gcc
      env: BUILDTYPE=Debug USE_SYSTEM_CURL=OFF
    - name: Linux GCC embedded-CURL Release
      os: linux
      dist: bionic
      compiler: gcc
      env: BUILDTYPE=Release USE_SYSTEM_CURL=OFF
    - name: Linux Clang system-CURL Debug
      os: linux
      dist: bionic
      compiler: clang
      env: BUILDTYPE=Debug
    - name: Linux Clang system-CURL Debug
      os: linux
      dist: bionic
      compiler: clang
      env: BUILDTYPE=Release
    - name: Linux (Alpine) GCC system-CURL Release
      os: linux
      sudo: true
      language: minimal
      before_install:
        - sudo docker run -dit --name quv --volume "${PWD}:/mnt/quv" --workdir /mnt/quv alpine:latest
        - sudo docker exec quv apk add build-base cmake ninja curl-dev --update-cache
      script: sudo docker exec quv sh -c "make && make test"
    - name: macOS Clang system-CURL Debug
      os: osx
      env: BUILDTYPE=Debug
    - name: macOS Clang system-CURL Release
      os: osx
      env: BUILDTYPE=Release
addons:
  apt:
    update: true
    packages:
      - ninja-build
  homebrew:
    update: true
    packages:
      - ninja
script:
  - make
  - ./build/quv -e "console.log(JSON.stringify(quv.versions))"
  - make test
branches:
  only:
    - master
