language: c
matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      env: BUILDTYPE=Debug
    - os: linux
      dist: bionic
      compiler: gcc
      env: BUILDTYPE=Release
    - os: linux
      dist: bionic
      compiler: clang
      env: BUILDTYPE=Debug
    - os: linux
      dist: bionic
      compiler: clang
      env: BUILDTYPE=Release
#    - os: linux
#      dist: bionic
#      addons:
#        apt:
#          update: true
#          packages:
#            - musl-tools
#            - ninja-build
#      env: BUILDTYPE=Debug CC=musl-gcc LINK=musl-gcc
    - os: osx
      env: BUILDTYPE=Debug
    - os: osx
      env: BUILDTYPE=Release
addons:
  apt:
    update: true
    packages:
      - ninja-build
  homebrew:
    update: true
    packages:
      - ninja
script:
  - make
  - make test
branches:
  only:
    - master
