language: c
matrix:
  include:
    - name: Linux GCC embedded-CURL Debug
      os: linux
      dist: bionic
      compiler: gcc
      env: BUILDTYPE=Debug USE_SYSTEM_CURL=OFF
    - name: Linux GCC embedded-CURL Release
      os: linux
      dist: bionic
      compiler: gcc
      env: BUILDTYPE=Release USE_SYSTEM_CURL=OFF
    - name: Linux Clang system-CURL Debug
      os: linux
      dist: bionic
      compiler: clang
      env: BUILDTYPE=Debug
    - name: Linux Clang system-CURL Release
      os: linux
      dist: bionic
      compiler: clang
      env: BUILDTYPE=Release
    - name: Linux (Alpine) GCC system-CURL Release
      os: linux
      sudo: true
      language: minimal
      before_install:
        - sudo docker run -dit --name tjs --volume "${PWD}:/mnt/tjs" --workdir /mnt/tjs alpine:latest
        - sudo docker exec tjs apk add build-base cmake curl-dev --update-cache
      script: sudo docker exec tjs sh -c "make && make test"
    - name: macOS Clang system-CURL Debug
      os: osx
      env: BUILDTYPE=Debug
    - name: macOS Clang system-CURL Release
      os: osx
      env: BUILDTYPE=Release
script:
  - make
  - ./build/tjs -e "console.log(JSON.stringify(tjs.versions))"
  - make test
branches:
  only:
    - master
