language: c
matrix:
  include:
    - name: Linux GCC embedded-CURL Debug
      os: linux
      dist: bionic
      compiler: gcc
      env: BUILDTYPE=Debug USE_SYSTEM_CURL=OFF
    - name: Linux GCC embedded-CURL Release
      os: linux
      dist: bionic
      compiler: gcc
      env: BUILDTYPE=Release USE_SYSTEM_CURL=OFF
    - name: Linux Clang system-CURL Debug
      os: linux
      dist: bionic
      compiler: clang
      env: BUILDTYPE=Debug
    - name: Linux Clang system-CURL Release
      os: linux
      dist: bionic
      compiler: clang
      env: BUILDTYPE=Release
script:
  - make
  - ./build/tjs -e "console.log(JSON.stringify(tjs.versions))"
  - make test
  - make test-advanced
branches:
  only:
    - master
