name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Build it
      run: make
    - name: Test it
      run: make test
