name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Prepare (Linux)
      if: matrix.operating-system == 'ubuntu-latest'
      run: sudo apt install -y libcurl4-openssl-dev ninja-build
    - name: Prepare (macOS)
      if: matrix.operating-system == 'macOS-latest'
      run: brew install ninja
    - name: Build it
      run: make
    - name: Test it
      run: make test
