name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
        buildType: [Debug, Release]
    env:
      BUILDTYPE: ${{ matrix.buildType }}
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Prepare (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt install -y libcurl4-openssl-dev
    - name: Build it
      run: make
    - name: Test it
      run: make test
    - name: Test it (advanced)
      run: make test-advanced
